services:
  server:
    build:
      context: .
      target: dev # target stage of the environment
    ports:
      - 5670:5670
    environment:
      PROTOCOL: http
      HOST: localhost
      PORT: 5670
    volumes:
      - .:/usr/src/app